version: '3.7'
services:
  bacnet_server: # Runs `bacserv` with a special command for unique ID.
    image: bacserv-rand:latest # Built from bacstack-with-rand.dockerfile
    
  nodered:
    image: nodered/node-red:latest
    ports:
        - "1880:1880"
    volumes:
      - nodered-data:/data
      
  wireshark:
    image: ffeldhaus/wireshark
    ports:
      - "14500:14500"
    cap_add:
      - NET_ADMIN

networks:
  default:
    driver: bridge

volumes:
  nodered-data: